// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActivePorts() {
  return window['go']['main']['App']['GetActivePorts']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function KillProcessWithPassword(arg1, arg2) {
  return window['go']['main']['App']['KillProcessWithPassword'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
