// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';
import {config} from '../models';

export function GetActivePorts():Promise<Array<sys.PortInfo>>;

export function GetConfig():Promise<config.Config>;

export function KillProcess(arg1:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;
